version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run:  
          name: Install Dependencies
          command: yarn
      - run: 
          name: deploy
          command: yarn deploy
workflows:
  deploy:
    jobs:
      - build-and-deploy